Lucas_Gaspard_projet_mvc/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lucas_Gaspard_projet_mvc.Data;
using Lucas_Gaspard_projet_mvc.Data.Model;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using LucasGaspardprojetmvc.Data.Migrations;

namespace Lucas_Gaspard_projet_mvc.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProductsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            ApplicationUser current_user = await _userManager.GetUserAsync(User);
            ViewBag.UserType = current_user?.Type ?? "";
            return _context.Products != null ?
                        View(await _context.Products.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Products'  is null.");
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ApplicationUser current_user = await _userManager.GetUserAsync(User);
            ViewBag.UserType = current_user?.Type ?? "";
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var products = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (products == null)
            {
                return NotFound();
            }

            return View(products);
        }

        // GET: Products/Create
        [Authorize]
        public async Task<IActionResult> Create()
        {
            ApplicationUser current_user = await _userManager.GetUserAsync(User);
            ViewBag.UserType = current_user?.Type ?? "";
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Titre,Fabricant,Prix,Info,Type")] Product products)
        {
            ApplicationUser current_user = await _userManager.GetUserAsync(User);
            if (ModelState.IsValid && (current_user.Type == products.Type || User.IsInRole("Administrator")))
            {
                _context.Add(products);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        // GET: Products/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            ApplicationUser current_user = await _userManager.GetUserAsync(User);
            ViewBag.UserType = current_user?.Type ?? "";
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (current_user.Type != product.Type && !User.IsInRole("Administrator"))
            {
                return RedirectToAction(nameof(Index));
            }
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titre,Fabricant,Prix,Info,Type")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            ApplicationUser current_user = await _userManager.GetUserAsync(User);
            var oldProdType = await _context.Products.Where(p => p.Id == id).Select(p => p.Type).FirstOrDefaultAsync();
            if (ModelState.IsValid && oldProdType == product.Type && (current_user.Type == product.Type || User.IsInRole("Administrator")))
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Products == null)
            {
                return NotFound();
            }
            ApplicationUser current_user = await _userManager.GetUserAsync(User);

            var product = await _context.Products.FirstOrDefaultAsync(m => m.Id == id);
            if (current_user.Type != product.Type && !User.IsInRole("Administrator"))
            {
                return RedirectToAction(nameof(Index));
            }
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Products == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Products'  is null.");
            }

            var product = await _context.Products.FindAsync(id);
            ApplicationUser current_user = await _userManager.GetUserAsync(User);
            if (ModelState.IsValid && _context.Products.Any(p => p.Type == product.Type) && (current_user.Type == product.Type || User.IsInRole("Administrator")))
            {
                if (product != null)
                {
                    _context.Products.Remove(product);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                }
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsExists(int id)
        {
            return (_context.Products?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Lucas_Gaspard_projet_mvc/Controllers/UsersController.cs
using Lucas_Gaspard_projet_mvc.Data;
using Lucas_Gaspard_projet_mvc.Data.Model;
using LucasGaspardprojetmvc.Data.Migrations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.CodeAnalysis.Differencing;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System;
using System.Linq;
using System.Runtime.InteropServices;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace Lucas_Gaspard_projet_mvc.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UsersController : Controller
    {
        private readonly List<string> acceptedTypes = new() { "Carrosserie", "Peinture", "Moteur" };
        private readonly List<string> acceptedRoles = new() { "Administrator", "Manager" };
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            List<ApplicationUser> users = await _context.Users.ToListAsync();
            List<(string, ApplicationUser)> usersWithRoles = new();
            foreach (ApplicationUser u in users)
            {
                if (_context.UserRoles.Any(ur => ur.UserId == u.Id))
                {
                    usersWithRoles.Add((_context.Roles.First(r => r.Id == _context.UserRoles.First(ur => ur.UserId == u.Id).RoleId).Name, u));
                }
                else
                {
                    usersWithRoles.Add(("", u));
                }
            }
            return _context.Users != null ?
                        View(usersWithRoles) :
                        Problem("Entity set 'ApplicationDbContext.Users'  is null.");
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            if (_context.Roles.First(r => r.Id == _context.UserRoles.First(ur => ur.UserId == user.Id).RoleId).Name.ToString() == "Administrator")
            {
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Type,UserName")] ApplicationUser UserType)
        {
            if (_context.Roles.First(r => r.Id == _context.UserRoles.First(ur => ur.UserId == UserType.Id).RoleId).ToString() == "Administrator")
            {
                return RedirectToAction(nameof(Index));
            }
            if (ModelState.IsValid && acceptedTypes.Any(t => t == UserType.Type) && acceptedRoles.Any(r => r == UserType.UserName))
            {
                try
                {
                    ApplicationUser user = await _context.Users.FindAsync(id);
                    IdentityUserRole<string> test = new()
                    {
                        UserId = UserType.Id,
                        RoleId = _context.Roles.First(r => r.Name == UserType.UserName).Id
                    };
                    user.Type = UserType.Type;
                    _context.Update(user);
                    _context.UserRoles.RemoveRange(_context.UserRoles.Where(ur => ur.UserId == UserType.Id));
                    _context.UserRoles.Add(test);
   
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(UserType);
        }
    }
}

Lucas_Gaspard_projet_mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lucas_Gaspard_projet_mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lucas_Gaspard_projet_mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lucas_Gaspard_projet_mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        @if (User.IsInRole("Administrator")) {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        }
                       
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Lucas_Gaspard_projet_mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>